repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: npm-run-format
        name: Run Prettier
        entry: npm run format
        language: system
        pass_filenames: false
        args: [--all-files]
      - id: npm-run-lint
        name: Run ESLint
        entry: npm run lint
        language: system
        pass_filenames: false
        args: [--all-files]
