version: "3.3"

services:
  paxi-popo-nest-dev:
    image: 151345152001.dkr.ecr.ap-northeast-2.amazonaws.com/paxi-popo-nest-api:latest
    ports:
      - 6100:4001
    secrets:
      - source: poapper_paxi_dev_popo_dotenv1
        target: /usr/src/app/.env
    deploy:
      placement:
        constraints:
          # deploy to manager node
          - node.role == manager
  paxi-popo-nest-prod:
    image: 151345152001.dkr.ecr.ap-northeast-2.amazonaws.com/paxi-popo-nest-api:vX.X.X
    ports:
      - 4100:4001
    secrets:
      - source: poapper_paxi_popo_dotenv_prod_1
        target: /usr/src/app/.env
    deploy:
      placement:
        constraints:
          # deploy to manager node
          - node.role == manager

secrets:
  poapper_paxi_dev_popo_dotenv1:
    external: true
  poapper_paxi_popo_dotenv_prod_1:
    external: true
